targets:
  $default:
    builders:
      freezed:
        enabled: true
      json_serializable:
        enabled: true
        options:
          explicit_to_json: true
          field_rename: snake_case
